spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
custom:
    image-directory-url: ${IMAGE_DIRECTORY}
jwt:
    token:
        secret: ${JWT_SECRET}